version: '3'

tasks:

  build:
    cmds:
      - docker build --tag fuseki --file fuseki.Dockerfile .
      - go build -v ./...

  up:
    cmds:
      - docker run -d -p 3030:3030 --name fuseki-server fuseki 
      - bash -c "while ! curl -s http://localhost:3030/$/ping; do sleep 5; done"
      - go run main.go
  
  down:
    cmds:
      - docker stop fuseki-server
      - docker rm fuseki-server