global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
  
  - job_name: 'backend'
    static_configs:
      - targets: ['host.docker.internal:8080']
  
  - job_name: 'fuseki'
    metrics_path: /$/metrics
    static_configs:
      - targets: ['host.docker.internal:3030']
